version: '2'

services:
  edit:
    restart: always
    image: theiaide/theia
    volumes:
      - "./p:/home/application:cached"
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=retrotope.411-source.com
      - LETSENCRYPT_HOST=retrotope.411-source.com
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./etc/nginx/htpasswd:/etc/nginx/htpasswd"
      - "./etc/nginx/vhost.d:/etc/nginx/vhost.d"
      - "./etc/nginx/sites-enabled:/etc/nginx/sites-enabled.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./etc/nginx/certs:/etc/nginx/certs"

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - nginx-proxy
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy
  web:
    restart: always
    image: jahbini/stagserv:four-point
    volumes_from: 
     - nginx-proxy
    volumes:
      - "${PWD}/sessions:/Stagserv-master/sessions"
      - "/home/retro/stagapp/public:/Stagserv-master/public"
      - "/home/retro/stagapp/app:/Stagserv-master/public/app"
    links:
      - db
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - VIRTUAL_HOST=huntingtest.retrotope.com
      - LETSENCRYPT_HOST=huntingtest.retrotope.com
      - VIRTUAL_PORT=3030
    expose:
      - 3030
  swagger:
    restart: always
    image: schickling/swagger-ui:latest
    expose:
      -  80
    environment:
      - VIRTUAL_HOST=stagapi.tell140.com
      - LETSENCRYPT_HOST=stagapi.tell140.com
      - VIRTUAL_PORT=80
      - API_URL=https://huntingtest.retrotope.com/api/swagger/retrotope.yaml
  db:
    restart: always
    image: mvertes/alpine-mongo:latest
    volumes:
      - "${PWD}/../db:/data/db" 
    expose:
      -  27017
