// Generated by CoffeeScript 1.10.0

/*
 * vim: et:ts=2:sw=2:sts=2
 */

(function() {
  var Event, Trajectory, base, env, keystone;

  keystone = require('keystone');

  Event = keystone.list('Event');

  Trajectory = keystone.list('Trajectory');

  env = keystone.get('env');

  if (typeof window !== "undefined" && window !== null) {
    base = window;
  }

  if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
    base = module;
  }

  base.exports = function(req, res) {
    var view, whichId;
    view = new keystone.View(req, res);
    console.log(req.body);
    whichId = req.body._id || new Event.model()._id.toString();
    delete req.body._id;
    console.log("Which id= ", whichId);
    console.log("NEW EVENT ", req.params);
    Event.model.findByIdAndUpdate(whichId, {
      $set: req.body
    }, {
      "new": true,
      upsert: true,
      setDefaultsOnInsert: true
    }, function(err, t) {
      var trajectory;
      if (err) {
        console.log(err);
      } else {
        trajectory = Trajectory.model.findByIdAndUpdate(t.trajectory, {
          $push: {
            events: t._id
          }
        }, function(err, trajectory) {
          return console.log("Trajectory update (" + err + ") -");
        });
        console.log('Event added ' + t._id + ' to the database.');
        res.status(200).send({
          message: "OK",
          _id: t._id
        });
      }
    });
  };

}).call(this);
