// Generated by CoffeeScript 1.12.7
(function() {
  var Session, _, base, keystone;

  keystone = require('keystone');

  Session = keystone.list('Session');

  _ = require('underscore');

  if (typeof window !== "undefined" && window !== null) {
    base = window;
  }

  if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
    base = module;
  }

  base.exports = function(req, res) {
    var view;
    view = new keystone.View(req, res);
    Session.model.findById(req.params.id).exec(function(err, session) {
      if (err) {
        console.log(err);
      } else {
        res.send(session);
      }
    });
    console.log('User model queried');
  };

}).call(this);
