// Generated by CoffeeScript 1.12.7
(function() {
  var Session, _, base, keystone;

  keystone = require('keystone');

  Session = keystone.list('Session');

  _ = require('underscore');

  if (typeof window !== "undefined" && window !== null) {
    base = window;
  }

  if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
    base = module;
  }

  base.exports = function(req, res) {
    var view;
    view = new keystone.View(req, res);
    Session.model.findById(req.params.id).exec(function(err, session) {
      var n, newSession;
      if (err) {
        console.log(err);
        res.status(404);
        res.send('not found');
      } else {
        console.log("session Found as", session);
        n = Object.assign({}, session._doc);
        console.log("session as n", n);
        delete n._id;
        n.readings = "";
        n.events = [];
        n.captureDate = null;
        newSession = new Session.model(n);
        newSession.save(function(err, newlyFormed) {
          if (err) {
            res.status(400);
          }
          console.log("newsession", newlyFormed);
          return res.send(newlyFormed);
        });
      }
    });
    console.log('User model queried');
  };

}).call(this);
