// Generated by CoffeeScript 1.10.0
(function() {
  var base, keystone;

  keystone = require('keystone');

  if (typeof window !== "undefined" && window !== null) {
    base = window;
  }

  if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
    base = module;
  }

  base.exports = function(req, res) {
    var view;
    view = new keystone.View(req, res);
    view.render('index');
  };

}).call(this);
