// Generated by CoffeeScript 1.12.7

/*
 * vim: et:ts=2:sw=2:sts=2
 */

(function() {
  var HandheldLogs, base, env, keystone;

  keystone = require('keystone');

  HandheldLogs = keystone.list('HandheldLogs');

  env = keystone.get('env');

  if (typeof window !== "undefined" && window !== null) {
    base = window;
  }

  if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
    base = module;
  }

  base.exports = function(req, res) {
    var name, query, view;
    name = req.params.id || req.body.name;
    view = new keystone.View(req, res);
    query = {
      name: name
    };
    delete req.body._id;
    HandheldLogs.model.findOneAndUpdate(query, req.body, {
      "new": true,
      upsert: true,
      setDefaultsOnInsert: true
    }, function(err, t) {
      if (err) {
        console.error(err);
        res.status(500).send({
          error: err
        });
      } else {
        console.log('Logfile  updated ' + t.name + ' to the database.');
        res.status(200).send(t);
      }
    });
  };

}).call(this);
