// Generated by CoffeeScript 1.9.1
(function() {
  var Protocol, _, base, keystone;

  keystone = require('keystone');

  Protocol = keystone.list('Protocol');

  _ = require('underscore');

  if (typeof window !== "undefined" && window !== null) {
    base = window;
  }

  if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
    base = module;
  }

  base.exports = function(req, res) {
    var view;
    view = new keystone.View(req, res);
    Protocol.model.find().exec(function(err, protocols) {
      if (err) {
        console.log(err);
      } else {
        res.send(protocols);
      }
    });
    console.log('Protocol model queried');
  };

}).call(this);
