// Generated by CoffeeScript 1.10.0

/*
 * vim: et:ts=2:sw=2:sts=2
 */

(function() {
  var Event, base, env, keystone;

  keystone = require('keystone');

  Event = keystone.list('Event');

  env = keystone.get('env');

  if (typeof window !== "undefined" && window !== null) {
    base = window;
  }

  if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
    base = module;
  }

  base.exports = function(req, res) {
    var t, view;
    view = new keystone.View(req, res);
    console.log(req.body);
    t = new Event.model(req.body);
    t.save(function(err) {
      if (err) {
        console.error(err);
        res.status(500).send({
          error: err
        });
      } else {
        console.log('Data Snip added ' + t._id + ' to the database.');
        res.status(200).send({
          message: "OK",
          _id: t._id
        });
      }
    });
  };

}).call(this);
