// Generated by CoffeeScript 1.12.7
(function() {
  var UnitConfigs, _, base, keystone;

  keystone = require('keystone');

  UnitConfigs = keystone.list('UnitConfig');

  _ = require('underscore');

  if (typeof window !== "undefined" && window !== null) {
    base = window;
  }

  if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
    base = module;
  }

  base.exports = function(req, res) {
    var view;
    view = new keystone.View(req, res);
    UnitConfigs.model.find().exec(function(err, configs) {
      if (err) {
        console.log(err);
      } else {
        res.send(configs);
      }
    });
  };

}).call(this);
