// Generated by CoffeeScript 1.12.7
(function() {
  var User, exports, keystone;

  keystone = require('keystone');

  User = keystone.list('User');

  exports = module.exports = function(done) {
    new User.model({
      name: {
        first: 'Harry',
        last: 'Saal'
      },
      email: 'harry@saal.org',
      password: 'Sniffer',
      canAccessKeystone: true
    }).save(done);
  };

}).call(this);
