// Generated by CoffeeScript 1.12.7

/*
 * vim: et:ts=2:sw=2:sts=2
 */

(function() {
  require('./unit-configs.js');

  require('./users.js');

  require('./clinics.js');

  require('./events.js');

  require('./sessions.js');

  require('./sensor-tags.js');

  require('./handhelds.js');

  require('./protocols.js');

  require('./logs.js');

}).call(this);
