// Generated by CoffeeScript 1.9.1

/*
 * vim: et:ts=2:sw=2:sts=2
 */

(function() {
  require('./users.js');

  require('./clinics.js');

  require('./trajectory.js');

  require('./sensor_tags.js');

}).call(this);
